# Generated by Django 5.1.3 on 2024-11-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordsUserAccount',
        ),
        migrations.DeleteModel(
            name='RecordsManager',
        ),
        migrations.DeleteModel(
            name='RecordsOfficer',
        ),
    ]
